# Generated by Django 5.0 on 2023-12-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="due_date",
            field=models.IntegerField(null=True),
        ),
    ]
