# Generated by Django 5.0 on 2023-12-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_alter_bill_due_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ACH", "ACH"),
                            ("DC", "Debit Card"),
                            ("CHK", "Check"),
                            ("CC", "Credit Card"),
                        ],
                        max_length=3,
                    ),
                ),
                ("check_number", models.PositiveIntegerField(null=True)),
                ("memo", models.CharField(max_length=199)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "running_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("ordinal_number", models.PositiveIntegerField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="bills.account",
                    ),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="bills.bill",
                    ),
                ),
            ],
        ),
    ]
