# Generated by Django 5.0 on 2023-12-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0005_alter_transaction_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="check_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
